### ISSUE TITLE
null ranks on high scores

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#327]
Sometimes Ranks are empty, and that can mess up the ios app.

I found out, since the app is crashing occasionally, that it seems like some High Scores can have no rank assigned to them. Is there anyway we could do a push to the server code that returns N/A for the rank? Also the site might want to default to N/A when the user is adding in High Scores.

Or, if that's no good, just delete all high scores (for all regions) in which there is no rank assigned?

**Comment by fmscode** [comment]
I know this is a old issue but I think it might be because the site doesn't check for Ranks when submitting a high score. I was just able to submit a high score with no score, rank, or initials. 
![screen shot 2015-01-14 at 3 02 20 pm](https://cloud.githubusercontent.com/assets/1703189/5746697/6356c0ea-9bff-11e4-8b2f-d872c9ee20fc.png)
