### ISSUE TITLE
Machines with duplicate names - not able to add one of them via autocomplete

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#378]
On the website (both mobile and desktop) if there are two machines with the same name, and you choose one of them to add to a location, the other will be added. I think the one with the lowest ID is always added. This only happens with the autocomplete, not the dropdown.

For now, I've changed the names of these machines (not sure if I got them all, though) to include the manufacturer in parentheses. This was also necessary to do because of this issue: https://github.com/scottwainstock/pbm-android/issues/52

For my own records:
Kiss
Star Trek
Harley-Davidson
Bonanza
Fireball
Fun-Fair
Soccer

**Comment by scottwainstock** [comment]
In order for this to work we're going to have to carry over the manufacturer and year info to the auto complete line.

So, right now if I click the autocomplete box for "Star Trek (Pro) (Stern, 2013)"... it puts "Star Trek (Pro)" into the autocomplete box.

I'd need it to put "Star Trek (Pro) (Stern, 2013)" into the box. I think that's the only way to make this work. My hesitancy with that approach is that people might end up typoing something after the click the autocomplete item, and we'll be overwhelmed with machine names like "Star Trek (Pro) (Stern, 2013".

You know what I mean? I'll keep thinking about alternatives. Maybe there's a way to submit the id of the machine instead of the name from the autocomplete.

**Comment by RyanTG** [comment]
Well, I wouldn't mind a solution that somehow also addresses the other issue I linked to. In the android app (not sure about iOS), if you type in Star Trek, you see:

Star Trek
Star Trek

And it's impossible to tell which is which. Note that this isn't the case at the moment because I changed all the machine names on the live site so there aren't any duplicates. And I don't want to change them back until that app issue is fixed.

I think this is why we were getting so many Kiss new machine names. People are typing in Kiss (Stern, 2015) because they weren't able to add the Kiss that's in the list. 

My feeling is that people won't be touching the textbox after the click. We don't see that happening now, so why would that change if the contents in the textbox were longer?

So I'm for carrying man/year over into the line. Especially if that leads the way toward addressing the other issue.

**Comment by RyanTG** [comment]
Oh, i see that you meant users might try to type in the entire name and then make a mistake. I just assumed they always just type in a few characters and then clock one of the s.

**Comment by RyanTG** [comment]
Of the results

**Comment by scottwainstock** [comment]
I think the way to address this via the mobile apps will be to update them to include the same (year, manufacturer) data in the autocomplete that people select.

**Comment by scottwainstock** [comment]
I think this is a much cleaner/safer implementation. It won't fix the mobile apps, but maybe we can aim for a similar implementation when we fix things there... let me know what you think.

6eec5b86dd13485befc73d4f7bcfbfe20b34f395

**Comment by RyanTG** [comment]
Ooh, yeah, that's sweet. Very elegant.

I feel like I&I asked Brian about including year/man on the app, and he shut me down. I'll look.

**Comment by RyanTG** [comment]
I can't find him commenting on that issue.
