### ISSUE TITLE
New England

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#392]
The Boston region bugs me. It's just too huge. And it's not "Boston" at all.

It's basically all of New England. But, we have other regions within New England: Burlington and Portland, ME.

I propose splitting the Boston data into new regions. The new regions are states: 
Massachusetts
New Hampshire
Rhode Island
Connecticut.

I don't want to include Vermont or Maine, because there are already regions within those states.

Can you do this? Example: Any location that has "RI" for state should be moved to the Rhode Island region.

And the Boston region should be changed to "Massachusetts". However, I should note that in the past I've experimented with changing the Name of a region, and it didn't sit well with the apps. So it may be necessary to create a brand new region called Massachusetts, move the locations to it, and then delete Boston. 

Full Name: Massachusetts
Name: massachusetts

Full Name: New Hampshire
Name: new-hampshire

Full Name: Rhode Island
Name: rhode-island

Full Name: Connecticut
Name: connecticut

I'll be the admin for them all, for now.

Also, I could start by creating these regions, if you'd like.

**Comment by RyanTG** [comment]
Note that there are a few locations in the Boston region that are in New York, Maine, or Vermont. I don't care if those are deleted. Or they can just move into the Massachusetts region, and I'll deal with them later.

**Comment by scottwainstock** [comment]
This is mostly done, I was going to leave the rest to you because I think it can all safely be done in the admin interface.

Orphaned regions:
glowing-dusk-5085::COBALT=> select * from zones where region_id=6;
 id  |        name        | region_id |         created_at         |         updated_at         | short_name | is_primary
-----+--------------------+-----------+----------------------------+----------------------------+------------+------------
 211 | New England North  |         6 | 2012-12-08 21:39:37.253573 | 2012-12-08 21:39:37.253573 |            | f
 212 | New England South  |         6 | 2012-12-08 21:39:49.915272 | 2012-12-08 21:39:49.915272 |            | f

Orphaned locations:
glowing-dusk-5085::COBALT=> select * from locations where region_id=6;
  id  |       name       |      street      |    city     | state |  zip  |     phone      |       lat       |       lon        |                      website                       |         created_at         |         updated_at         | zone_id | region_id | location_type_id | description | operator_id | date_last_updated
------+------------------+------------------+-------------+-------+-------+----------------+-----------------+------------------+----------------------------------------------------+----------------------------+----------------------------+---------+-----------+------------------+-------------+-------------+-------------------
 3203 | Brattleboro Bowl | 865 Putney Rd.   | Brattleboro | VT    | 05301 | (802) 257-1177 | 42.877910000000 | -72.558600000000 | http://www.brattleborobowl.com/                    | 2012-11-07 23:22:56.261776 | 2015-10-09 20:57:21.581785 |     211 |         6 |               10 |             |             | 2015-10-09
 3787 | Smitty's Cinema  | 1364 Main Street | Stanford    | ME    | 04073 | (207) 490-2148 | 43.414081000000 | -70.747286000000 | http://www.smittyscinema.com/showtimes-Sanford.asp | 2013-07-13 18:36:34.999733 | 2015-07-19 21:50:17.627878 |     211 |         6 |                8 |             |             |
 5397 | Half Moon Bar    | 48 S Front St    | Hudson      | NY    | 12534 | 518-828-1562   | 42.254976500000 | -73.797203300000 | http://thehalfmoonhudson.com/                      | 2015-01-21 03:21:16.242267 | 2015-10-09 07:27:19.828517 |     207 |         6 |                4 |             |             | 2015-10-09
(3 rows)

**Comment by RyanTG** [comment]
For my records

Brattleboro: rollercoaster
Half moon: dracula
Smitty: LOTR

**Comment by RyanTG** [comment]
Deleting boston..

**Comment by RyanTG** [comment]
Need to add myself (or others) as admins.

**Comment by RyanTG** [comment]
I'm da admin. We put a call out for locals.
