### ISSUE TITLE
Country field

### ISSUE THREAD

**Issue by RyanTG** [scottwainstock/pbm#967]
And hopefully we can autopopulate existing locations by going through the regions.

Canada:
bc
toronto
manitoba
calgary
montreal
ottawa

and location id: 10173 (regionless)

Australia:
brisbane

Everything else (including regionless) is United States.

**Comment by scottwainstock** [comment]
I added it to suggested location and location. It's only exposed on the site right now via the location submission form, but it's available to call on location/suggested_location as "country".

https://github.com/scottwainstock/pbm/commit/3035d5673ffd5474ccd2d2b46b58b7248807c871

**Comment by scottwainstock** [comment]
The SQL for updating is...

update locations set country='CA' where region_id in (select id from regions where name in ('bc', 'toronto', 'manitoba', 'calgary', 'montreal', 'ottawa');

update locations set country='CA' where id= 10173;

update locations set country='AU' where region_id in (select id from regions where name='brisbane');

I'm not sure that "everything else" thing is true anymore, is it? If so:
update locations set country='US' where country is null;

Maybe we can run all the above SQL and just manually correct the couple that have come in for England and Norway or whatever? I haven't run any of this SQL because I figured we should circle up on it first.

**Comment by RyanTG** [comment]
Yeah, the “everything else” isn’t true anymore. But there are only like four everything else locations, so I agree that we can manually change them after.

**Comment by RyanTG** [comment]
````
update locations set country='AU' where region_id in (select id from regions where name='brisbane');
UPDATE 61
 update locations set country='CA' where region_id in (select id from regions where name in ('bc', 'toronto', 'manitoba', 'calgary', 'montreal', 'ottawa'));
UPDATE 264
update locations set country='CA' where id= 10173;
UPDATE 1
update locations set country='US' where country is null;
UPDATE 4977
````

And manually changed the others.
